version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self.yml

jobs:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
    - php: 7.3
      env:
        - PHPUNIT_COVERAGE_TEST=1
    - php: 7.4
      env:
        - PHPUNIT_TEST=1
