language: php

matrix:
  include:
  - php: 7.1
    env: PHPUNIT_COVERAGE_TEST=1
  - php: 7.2
    env: PHPUNIT_TEST=1 PHPCS_TEST=1
  - php: 7.3
    env: PHPUNIT_TEST=1

before_script:
  # php setup
  - phpenv rehash
  - export PATH=~/.composer/vendor/bin:$PATH

  # Install
  - composer validate
  - composer install --prefer-dist

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=PSR12 bin/ src/ tests/; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
