version: '3.7'

x-build-args: &build-args
  UID: ${USER_ID}

x-entrypoint: &entrypoint
  - /bin/bash
  - /app/docker/entrypoint.sh

x-volumes: &volumes
  - '..:/app'
  - './cache/composer:/home/cow/.composer/cache'

x-debug-env-var: &x-debug-env-var 'remote_enable=1 remote_mode=req remote_port=9000 remote_host=127.0.0.1 remote_connect_back=0'

x-build-context: &build-context .

x-wdir: &wdir /app

services:
  cow_dev:
    build:
      context: *build-context
      target: dev
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint

  cow_debug:
    build:
      context: *build-context
      target: debug
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment:
      DEBUG_COW: 1
      XDEBUG_CONFIG: *x-debug-env-var

  cow_test:
    build:
      context: *build-context
      target: dev
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment:
      TEST_COW: 1
      DEBUG_COW: 1

  cow_debug_test:
    build:
      context: *build-context
      target: debug
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment:
      TEST_COW: 1
      DEBUG_COW: 1
      XDEBUG_CONFIG: *x-debug-env-var

  cow_phpcs:
    build:
      context: *build-context
      target: dev
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment:
      PHPCS_COW: 1
