version: '3.7'

x-build-args: &build-args
  UID: ${USER_ID}

x-entrypoint: &entrypoint
  - /bin/bash
  - /app/docker/entrypoint.sh

x-volumes: &volumes
  - '..:/app'
  - './cache/composer:/home/cow/.composer/cache'
  - '${GIT_CONFIG}:/home/cow/.gitconfig:ro'
  - '${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}:rw'
  - '~/.transifexrc:/home/cow/.transifexrc'

x-debug-env-var: &x-debug-env-var 'remote_enable=1 remote_mode=req remote_port=${XDEBUG_PORT} remote_host=${XDEBUG_HOST} remote_connect_back=0'

x-build-context: &build-context .

x-wdir: &wdir /app

x-environment: &environment
  SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
  XDEBUG_CONFIG: *x-debug-env-var


services:
  # Using the stable prebuilt image
  stable:
    image: docker.pkg.github.com/silverstripe/cow/master:latest
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment: *environment

  # Build a new local image WITHOUT Xdebug and run localhost version of Cow in there
  dev:
    build:
      context: *build-context
      target: base
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment: *environment

  # Build a new local image WITH Xdebug and run localhost version of Cow in there
  debug:
    build:
      context: *build-context
      target: debug
      args: *build-args
    working_dir: *wdir
    network_mode: 'host'
    volumes: *volumes
    entrypoint: *entrypoint
    environment: *environment